### ISSUE TITLE
Detect if banner is already active

### ISSUE THREAD

**Issue by vycoder** [DTX-Elliot/capacitor-admob-advanced#7]
Hi, I was wondering if it would be possible to implement a method to check whether the banner ad is already active, or at least internally check if it's already up before showing the banner ad.

The thing is my code had to listen to various events and should show/remove banner accordingly but everytime It happens to call `Admob.showAdBanner` twice, app crashes with this error:

```java
Process: com.my.app, PID: 8912
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4976)
        at android.view.ViewGroup.addView(ViewGroup.java:4807)
        at android.view.ViewGroup.addView(ViewGroup.java:4747)
        at android.view.ViewGroup.addView(ViewGroup.java:4720)
        at com.devutex.admobadvanced.AdMobAdvanced$4.run(AdMobAdvanced.java:421)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by DTX-Elliot** [comment]
In my own apps I use an internal check on the Ionic side to see if I have already "shown" (loaded) the banner and therefore should use the resume or the show method. I find it more useful for the app to know if it has loaded a banner or not rather than the plugin, it gives you more flexibility as a developer as to how you want your app to flow with different pages requiring a banner or not. With regards to the error, I'll release a patch soon to prevent the app crashing if you attempt to show multiple banners, but for now I won't add in returning any data on the show plugin. Hope that helps

**Comment by vycoder** [comment]
@DTX-Elliot Thanks! I think preventing it from crashing will work just fine for my purposes. I personally prefer looking at plugins/libraries as an external blackbox so I avoid introducing flags within my app that controls or depend on an external lugin. But yeah, I was assuming that you can only have one banner ad and thought it would be useful to have a way to query if I already show it.
